### ISSUE TITLE
Tweet actions overlapping tweet.

### ISSUE THREAD

**Issue by rajeevedmonds** [ronilaukkarinen/tweeten-tweetbot-theme#1]
![2018-07-19_204431](https://user-images.githubusercontent.com/1507156/42951834-bd3af080-8b94-11e8-8ec7-4a335bc12563.png)

After TweekDeck update, tweet actions have started overlapping some tweets.

Just noticed, it's happening for both single line and few multi-line tweets.

**Comment by rollecode** [comment]
Thanks for the report! However, that's intended behaviour, because they are otherwise invisible when hovering full size image tweets. I'm going to figure out a better way to implement this.

**Comment by rajeevedmonds** [comment]
Ok! Looking forward to one of the upcoming releases. Thanks for this beautiful theme.

**Comment by rajeevedmonds** [comment]
Thanks for the update! Looks good now 😀

**Comment by rollecode** [comment]
No probs, glad you like it!
